Fixed issues with timezones, browsers, and SQL
This fixes 3 bugs:

1. The way I was importing date-fns wasn't working in the browser - causing errors like:
  Error: Cannot find module 'date-fns/add'
  - This fix for this was to import the whole module, which is not desirable but is a solution
2. For people in non-UTC timezones, the relDateToAbsolute function was returning dates localised to their timezone, resulting in the error:
  AssertionError: expected '2022-02-27T11:22:40+01:00' to match /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z/
  - The fix for this is to not use date-fns format functions, as there is no way to force UTC with these
  - The fix I've used is to use Date.toISOString() which always outputs UTC time
3. Queries doing comparisons on the format /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z/ actually only work in MySQL
  - The fix for this is to change the format to /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/
  - This works in both MySQL and SQLite3

TODO:
- We should write tests to prove the date formatter is doing the right thing